<?php
/**
 * Shared bootstrap for the admin area and the form endpoint.
 *
 * Holds the database connection, session hardening, CSRF helpers, the login
 * gate and the brute-force throttle. Nothing here echoes anything, so it is
 * safe to include before sending headers.
 */

declare(strict_types=1);

const DATA_DIR    = __DIR__ . '/../data';
const DB_FILE     = DATA_DIR . '/submissions.sqlite';
const CONFIG_FILE = DATA_DIR . '/config.php';

/** Failed logins allowed from one IP before it is locked out. */
const MAX_LOGIN_ATTEMPTS = 5;
/** How long that lockout lasts, in seconds. */
const LOCKOUT_SECONDS    = 900;   // 15 minutes

/* -------------------------------------------------------------------------
   Database
   ---------------------------------------------------------------------- */

function db(): PDO
{
    static $pdo = null;
    if ($pdo instanceof PDO) {
        return $pdo;
    }

    if (!is_dir(DATA_DIR)) {
        mkdir(DATA_DIR, 0750, true);
    }

    $pdo = new PDO('sqlite:' . DB_FILE);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);

    $pdo->exec('
        CREATE TABLE IF NOT EXISTS submissions (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT    NOT NULL,
            source     TEXT    NOT NULL,
            name       TEXT    NOT NULL,
            email      TEXT    NOT NULL,
            phone      TEXT    NOT NULL DEFAULT "",
            message    TEXT    NOT NULL DEFAULT "",
            extra      TEXT    NOT NULL DEFAULT "{}",
            ip         TEXT    NOT NULL DEFAULT "",
            is_read    INTEGER NOT NULL DEFAULT 0
        )');
    $pdo->exec('CREATE INDEX IF NOT EXISTS idx_created ON submissions (created_at DESC)');

    $pdo->exec('
        CREATE TABLE IF NOT EXISTS login_attempts (
            ip       TEXT NOT NULL,
            at       INTEGER NOT NULL
        )');
    $pdo->exec('CREATE INDEX IF NOT EXISTS idx_attempt_ip ON login_attempts (ip, at)');

    return $pdo;
}

/* -------------------------------------------------------------------------
   Admin account
   ---------------------------------------------------------------------- */

function admin_account(): ?array
{
    if (!is_file(CONFIG_FILE)) {
        return null;
    }
    $cfg = require CONFIG_FILE;
    return (is_array($cfg) && !empty($cfg['email']) && !empty($cfg['hash'])) ? $cfg : null;
}

function admin_exists(): bool
{
    return admin_account() !== null;
}

function save_admin_account(string $email, string $password): void
{
    if (!is_dir(DATA_DIR)) {
        mkdir(DATA_DIR, 0750, true);
    }
    $php = "<?php\n// Generated by admin/setup.php — do not edit by hand.\nreturn "
         . var_export([
             'email' => $email,
             'hash'  => password_hash($password, PASSWORD_DEFAULT),
           ], true)
         . ";\n";
    file_put_contents(CONFIG_FILE, $php, LOCK_EX);
    chmod(CONFIG_FILE, 0640);
}

/* -------------------------------------------------------------------------
   Session
   ---------------------------------------------------------------------- */

function is_https(): bool
{
    return (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https')
        || (($_SERVER['SERVER_PORT'] ?? '') === '443');
}

function boot_session(): void
{
    if (session_status() === PHP_SESSION_ACTIVE) {
        return;
    }
    session_set_cookie_params([
        'lifetime' => 0,
        'path'     => '/',
        'secure'   => is_https(),   // never send the cookie over plain HTTP
        'httponly' => true,         // JavaScript cannot read it
        'samesite' => 'Strict',     // not sent on cross-site requests (CSRF)
    ]);
    session_name('usftf_admin');
    session_start();
}

function is_logged_in(): bool
{
    boot_session();
    return !empty($_SESSION['admin_email']);
}

function require_login(): void
{
    if (!is_logged_in()) {
        header('Location: index.php');
        exit;
    }
}

/* -------------------------------------------------------------------------
   CSRF
   ---------------------------------------------------------------------- */

function csrf_token(): string
{
    boot_session();
    if (empty($_SESSION['csrf'])) {
        $_SESSION['csrf'] = bin2hex(random_bytes(32));
    }
    return $_SESSION['csrf'];
}

function csrf_ok(?string $sent): bool
{
    boot_session();
    return !empty($_SESSION['csrf']) && is_string($sent)
        && hash_equals($_SESSION['csrf'], $sent);
}

/* -------------------------------------------------------------------------
   Brute-force throttle
   ---------------------------------------------------------------------- */

function client_ip(): string
{
    return (string)($_SERVER['REMOTE_ADDR'] ?? '0.0.0.0');
}

function attempts_recent(string $ip): int
{
    $stmt = db()->prepare(
        'SELECT COUNT(*) c FROM login_attempts WHERE ip = ? AND at > ?');
    $stmt->execute([$ip, time() - LOCKOUT_SECONDS]);
    return (int)$stmt->fetch()['c'];
}

function is_locked_out(string $ip): bool
{
    return attempts_recent($ip) >= MAX_LOGIN_ATTEMPTS;
}

function record_failed_login(string $ip): void
{
    db()->prepare('INSERT INTO login_attempts (ip, at) VALUES (?, ?)')
        ->execute([$ip, time()]);
    // opportunistic cleanup so the table cannot grow forever
    db()->prepare('DELETE FROM login_attempts WHERE at < ?')
        ->execute([time() - LOCKOUT_SECONDS * 4]);
}

function clear_login_attempts(string $ip): void
{
    db()->prepare('DELETE FROM login_attempts WHERE ip = ?')->execute([$ip]);
}

/* -------------------------------------------------------------------------
   Output escaping — every submission field is attacker-controlled text
   ---------------------------------------------------------------------- */

function e(?string $v): string
{
    return htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function human_date(string $iso): string
{
    $ts = strtotime($iso);
    return $ts ? date('j M Y, H:i', $ts) : $iso;
}
